### PR TITLE
facs: Fixed cell treatment selection bug

### LINKED ISSUE #639: Bug in flow cytometry cell treatment options
screenshot from 2016-06-15 12-03-35

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?

Fix #639 
#### What's this PR do?

Fix the warning logic on selection of analysis type. Add logic to selection of cell treatment to check if more options of analysis or condition are available for this cell treatment.
#### How should this be manually tested?

To recreate the bug, define an assignment as described in issue #639. Preview the assignment. In 'Sample Prep' step of FlowCytometry try to select all three possible variations of cell treatment, analysis, and condition. The bug will not let you select the third lane, saying that this option was already selected.

### CODE REVIEW

**Comment by noisecapella** [comment]
Functionality looks good

File: html_app/ui/FacsView.js [hunk 1]
```diff
@@ -69,31 +69,50 @@ scb.ui.static.FacsView.scb_f_facs_cell_treatment_radio = function(element, event
     alert("INVALID ELEMENT!");
   }
   /* val is 'fixed' or 'live' */
-  var val = $(element).val();
+  var live = $(element).val();
   /* if lane does not exist equals to '' */
   var lane_id = $(element).attr('lane_id');
   var cell_treatment_id = $(element).attr('cell_treatment_id');
   /* map_key is "cell_treatment.id_[lane.id]" */
   var map_key = $(element).attr('data-map_key');
```
Comment (noisecapella) [inline html_app/ui/FacsView.js]: Feel free to leave as is but this can also be written as `$(element).data('map_key')`

**Comment by noisecapella** [comment]
Code looks good :+1:
