### PR TITLE
fix logout

### LINKED ISSUE #21: When signing out, user is redirected to starcellbio.mit.edu
This should be changed to redirect to the current server. 

Steps to reproduce:

On a scbdev.mit.edu or a VM running starcellbio,
1. Sign in 
2. Sign out (using the button in the upper right)

You will be redirected to https://starcellbio.mit.edu/#view=homepage

Expected behavior: redirected to /#view=homepage on the current server

### PR DESCRIPTION
**Pull request by annagav**
Fix #21

### CODE REVIEW

File: html_app/ui/MainFrame.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ scb.ui = scb.ui || {};
 scb.ui.static = scb.ui.static || {};
 
 scb.ui.static.MainFrame = scb.ui.static.MainFrame || {};
-scb.ui.static.MainFrame.LOGOUT_URL = '/accounts/logout/';
+scb.ui.static.MainFrame.LOGOUT_URL = '/scb/logout/';
```
Comment (noisecapella) [inline html_app/ui/MainFrame.js:7]: How do I get to this? After I log in on the main page I still see 'Sign in'. When I click it it says that my account is confirmed

**Comment by noisecapella** [comment]
Just the question, functionality looks good otherwise

**Comment by noisecapella** [comment]
I've confirmed this with the instructor and student users so feel free to merge :+1:
